services:
  - type: web
    name: multistream
    env: python
    buildCommand: |
      cd client
      npm install
      npm run build
    startCommand: gunicorn api.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
